"""Type stubs for pygame package."""

from typing import Any

def init() -> None: ...
def quit() -> None: ...

class Surface:
    """Pygame Surface class."""

    def blit(self, source: Surface, dest: tuple[int, int]) -> None: ...

class display:
    """Pygame display module."""

    @staticmethod
    def set_mode(size: tuple[int, int]) -> Surface: ...
    @staticmethod
    def set_caption(title: str) -> None: ...
    @staticmethod
    def flip() -> None: ...

class image:
    """Pygame image module."""

    @staticmethod
    def frombuffer(buffer: bytes, size: tuple[int, int], format: str) -> Surface: ...

class transform:
    """Pygame transform module."""

    @staticmethod
    def scale(surface: Surface, size: tuple[int, int]) -> Surface: ...

class event:
    """Pygame event module."""

    @staticmethod
    def get() -> list[Any]: ...

class time:
    """Pygame time module."""

    class Clock:
        def __init__(self) -> None: ...
        def tick(self, framerate: int) -> int: ...

# Constants
class K_UP: ...
class K_DOWN: ...
class K_LEFT: ...
class K_RIGHT: ...
class K_w: ...
class K_s: ...
class K_a: ...
class K_d: ...
class K_q: ...
class K_ESCAPE: ...
class QUIT: ...
class KEYDOWN: ...
class KEYUP: ...
