"""Type stubs for PIL.ImageFont module."""

from typing import Any

class FreeTypeFont: ...
class ImageFont: ...

# Module-level functions
def truetype(font: str, size: int) -> Any: ...
def load_default() -> Any: ...
